# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gowalla}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wynn Netherland"]
  s.date = %q{2010-05-06}
  s.description = %q{Ruby wrapper for the Gowalla API}
  s.email = %q{wynn.netherland@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "changelog.md",
     "gowalla.gemspec",
     "lib/gowalla.rb",
     "lib/gowalla/client.rb",
     "test/fixtures/categories.json",
     "test/fixtures/category.json",
     "test/fixtures/challenges.json",
     "test/fixtures/checkin.json",
     "test/fixtures/events.json",
     "test/fixtures/find_spots.json",
     "test/fixtures/find_trips.json",
     "test/fixtures/friend_requests.json",
     "test/fixtures/friends.json",
     "test/fixtures/friends_recent.json",
     "test/fixtures/item.json",
     "test/fixtures/items.json",
     "test/fixtures/me.json",
     "test/fixtures/missing_items.json",
     "test/fixtures/new_spot.json",
     "test/fixtures/pins.json",
     "test/fixtures/potential_twitter_friends.json",
     "test/fixtures/spot.json",
     "test/fixtures/spots.json",
     "test/fixtures/spots_by_category.json",
     "test/fixtures/stamps.json",
     "test/fixtures/top_spots.json",
     "test/fixtures/trip.json",
     "test/fixtures/trips.json",
     "test/fixtures/user.json",
     "test/fixtures/vaulted_items.json",
     "test/fixtures/visited_spots.json",
     "test/helper.rb",
     "test/test_gowalla.rb"
  ]
  s.homepage = %q{http://github.com/pengwynn/gowalla}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby wrapper for the Gowalla API}
  s.test_files = [
    "test/helper.rb",
     "test/test_gowalla.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hashie>, [">= 0.1.3"])
      s.add_runtime_dependency(%q<httparty>, [">= 0.5.0"])
      s.add_development_dependency(%q<shoulda>, [">= 2.10.1"])
      s.add_development_dependency(%q<jnunemaker-matchy>, ["= 0.4.0"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.5"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<hashie>, [">= 0.1.3"])
      s.add_dependency(%q<httparty>, [">= 0.5.0"])
      s.add_dependency(%q<shoulda>, [">= 2.10.1"])
      s.add_dependency(%q<jnunemaker-matchy>, ["= 0.4.0"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.5"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<hashie>, [">= 0.1.3"])
    s.add_dependency(%q<httparty>, [">= 0.5.0"])
    s.add_dependency(%q<shoulda>, [">= 2.10.1"])
    s.add_dependency(%q<jnunemaker-matchy>, ["= 0.4.0"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.5"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

